model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "/var/run/postgresql",
  "/home/elmeri/.local/share/Odoo",
  "/home/elmeri/Odoo",
]

[projects."/home/elmeri/Odoo/19/sahkoinfo_addons/sprintit_gimlet_lms"]
trust_level = "trusted"

[projects."/home/elmeri/Odoo/19/sahkoinfo_addons/sprintit_digital_materials"]
trust_level = "trusted"

[projects."/home/elmeri/Odoo/19/sahkoinfo_addons"]
trust_level = "trusted"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.3-codex"
